apiVersion: v1
kind: Pod
metadata:
  name: aman-test
  labels:
    tier: backend
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: dedicated
            operator: In
            values:
            - karpenter
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "karpenter"
    effect: "NoSchedule"      
  containers:
    - name: nginx
      image: nginx
